name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
#    - name: Set up Docker Buildx
#      id: buildx
#      uses: crazy-max/ghaction-docker-buildx@v1
#      with:
#        version: latest
    -
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
        
    - name: Build the Docker image
      run: |
        docker buildx build --platform=linux/amd64,linux/arm/v6,linux/arm/v7 . \
        --file Dockerfile --tag bencardinal/assistant-relay:$(date +%s)
