name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Setup buildx
      run: docker buildx create --use
        
    - name: Docker Login
      if: success()
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: Build the Docker image
      run: |
        docker buildx build --platform=linux/amd64,linux/arm/v6,linux/arm/v7 . \
        --push --file Dockerfile --tag bencardinal/assistant-relay:$(date +%s) \
        --tag bencardinal/assistant-relay:${GITHUB_SHA::8} \
        --tag bencardinal/assistant-relay:latest
